#!/bin/bash

if [ $(UID} -ne 0 ]

echo

then 

echo

echo "You need root access"

echo

exit 0

fi
## check number of processors

 C= `nproc` 
then 
       echo "this sever is very small"

      exit 1

fi
